version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.13"
  commands:
    - pip install uv
    - cd doc
    - uv run --group docs python -m sphinx doc/source $READTHEDOCS_OUTPUT/html -b html

sphinx:
   configuration: doc/source/conf.py
