[tool.versioneer]
VCS = "git"
style = "pep440-pre"
versionfile_source = "flask_limiter/_version.py"
versionfile_build = "flask_limiter/_version.py"
parentdir_prefix = "flask-limiter-"
tag_prefix = ""

[tool.ruff]
line-length=88
indent-width = 4
exclude = ["_version.py"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
