[tool.versioneer]
VCS = "git"
style = "pep440-pre"
versionfile_source = "flask_limiter/_version.py"
versionfile_build = "flask_limiter/_version.py"
parentdir_prefix = "flask-limiter-"
tag_prefix = ""

[tool.mypy]
strict = true
check_untyped_defs = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
show_error_codes = true
warn_return_any = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = [
    "werkzeug",
    "flask_limiter._compat.*",
    "flask_limiter._version",
]

ignore_errors = true

[tool.ruff]
line-length=100
indent-width = 4
exclude = ["_version.py"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
