[pytest]
norecursedirs = build *.egg
markers =
    unit: mark a test as a unit test.
    docker: mark a test as requiring docker services (redis, memcached, mongodb).
addopts =
    --verbose
    --tb=short
    --capture=no
    -rfEsxX
    --cov=flask_limiter
